"""Add resource limits to plans

Revision ID: b36cfb3402ac
Revises: c290295f5a03
Create Date: 2025-10-12 10:58:38.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36cfb3402ac'
down_revision: Union[str, None] = 'c290295f5a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('ram_mb', sa.BigInteger(), nullable=False, server_default='256'))
    op.add_column('plans', sa.Column('cpu_vcore', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('plans', sa.Column('disk_gb', sa.BigInteger(), nullable=False, server_default='1'))
    op.add_column('plans', sa.Column('max_services', sa.BigInteger(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'max_services')
    op.drop_column('plans', 'disk_gb')
    op.drop_column('plans', 'cpu_vcore')
    op.drop_column('plans', 'ram_mb')
    # ### end Alembic commands ###