"""Add service model

Revision ID: d617fdfb66cd
Revises: 1901f26d9020
Create Date: 2025-10-11 19:22:41.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd617fdfb66cd'
down_revision: Union[str, None] = '1901f26d9020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_type', sa.Enum('MINECRAFT_PAPER', 'MINECRAFT_FORGE', 'MINECRAFT_VANILLA', 'PYTHON_BOT', 'NODEJS_APP', name='servicetype'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('docker_container_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docker_container_id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###